.TH "todo" 3 "Mon Apr 20 2015" "CSD201 Algos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBFile \fBsort\&.c\fP \fP" 1c
Allow user to pass test cases in the test functions  
.IP "\fBFile \fBsort\&.h\fP \fP" 1c
Add time complexity for each sort function in their documentation 
.PP

